version: "3"

services:
  frontend:
    build: ../
    environment:
      - WATCHPACK_POLLING=true
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ../:/app